# Generated by Django 5.2.5 on 2026-02-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='catigory',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Important', 'Important'), ('Business', 'Business')], default='Personal', max_length=15),
        ),
    ]
